# Generated by Django 4.1.7 on 2023-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("dob", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "male"), ("Female", "female")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("mobile", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("resume", models.FileField(null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("position", models.CharField(max_length=200, null=True)),
                ("description", models.CharField(max_length=4000, null=True)),
                ("salary", models.IntegerField(null=True)),
                ("experience", models.IntegerField(null=True)),
                ("Location", models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
