# Generated by Django 4.1.7 on 2023-03-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobPortal", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name_plural": "vacancies"},
        ),
    ]
