# Generated by Django 4.1.7 on 2023-03-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobPortal", "0003_alter_vacancy_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candidates",
            new_name="Candidate",
        ),
    ]
