# Generated by Django 4.1.7 on 2023-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="surname",
            field=models.CharField(max_length=150, verbose_name="Surname"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(max_length=150, verbose_name="User Type"),
        ),
    ]
